{% set name = "tinygltf" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/syoyo/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 29ca18191062124bf318cc99d9dc51071f6ac6f14ab1d15d10702ec26fac660e

build:
  number: 0
  noarch: generic
  script:
    - mkdir $PREFIX/include                          # [unix]
    - cp $SRC_DIR/*.h $PREFIX/include                # [unix]
    - cp $SRC_DIR/*.hpp $PREFIX/include              # [unix]
    - mkdir $PREFIX\include                          # [win]
    - xcopy /S %SRC_DIR%\*.h %LIBRARY_INC%           # [win]
    - xcopy /S %SRC_DIR%\*.hpp %LIBRARY_INC%         # [win]

test:
  commands:
    - test -f ${PREFIX}/include/tiny_gltf.h          # [unix]
    - if not exist %LIBRARY_INC%\tiny_gltf.h exit 1  # [win]

about:
  home: https://github.com/syoyo/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Header only C++11 tiny glTF 2.0 library.
  description: |
    TinyGLTF is a header only C++11 glTF 2.0 https://github.com/KhronosGroup/glTF library.
  dev_url: https://github.com/syoyo/{{ name }}

extra:
  recipe-maintainers:
    - benjaminrwilson
